"""First migration

Revision ID: 0823d1434b1b
Revises: 4cf64ea09beb
Create Date: 2023-12-23 16:28:50.031501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0823d1434b1b'
down_revision = '4cf64ea09beb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
